### ISSUE TITLE
Description lists incorrect repository as the official Solus repository

### ISSUE THREAD

**Issue by yerbestpal** [ThanosApostolou/solus-wine-staging-repository#3]
The official Solus repository is `https://packages.solus-project.com/shannon/eopkg-index.xml.xz`, not `http://raw.github.com/ThanosApostolou/solus-mate-unstable-repository/stable/eopkg-index.xml.xz`. This leaves users with no access to the official repositories.

**Comment by ThanosApostolou** [comment]
Oops sorry for that. fixed.
